pipeline {
    agent any
    stages {
        stage('build') {`
            steps {
                sh "oc start-build simple-java-app -w"
            }
        }
        stage('deploy') {
            steps {
                sh "oc rollout latest dc/simple-java-app"
            }
        }
    }
}
